# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac72c3bba5f28ac2b288e466793c534921e0357a8efb9e6c66590c4862edd1a19aa875ff461a8207a32637e321119c494db3a2e8011168e2c2e1bc59c4ab7dc3

test:
  secret_key_base: 2bfbac0059a733bc6213bbb214633e5b78762cd83a4e0e44a13bbf87b7894129087802448999ff7abf557bd2008d1f41161502a9df9e76f0f02764324c114aa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
